# -*- coding: utf-8 -*-
"""mapa trm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q2Gs6OxsrLfNJBdGyF91yTPkjyQl4cS-
"""

!pip install geopandas

import geopandas as gpd
import matplotlib.pyplot as plt

mapa = "/content/drive/MyDrive/cevs/mapas/RS_Municipios_2022/RS_Municipios_2022.shp"
mapa_rs = gpd.read_file(mapa)

print(mapa_rs.columns)

municipios_verdes = ["Alvorada", "Bagé", "Cachoeira do Sul", "Canoas", "Charqueadas", "Gravataí", "Palmeira das Missões", "Passo Fundo", "Pelotas", "Porto Alegre", "Rio Grande", "Santa Maria", "São Borja", "São Leopoldo", "Uruguaiana", "Viamão"]
mapa_rs['cor'] = 'whitesmoke'
mapa_rs.loc[mapa_rs['NM_MUN'].isin(municipios_verdes), 'cor'] = 'mediumseagreen'

fig, ax = plt.subplots(1, 1, figsize=(12, 15))
mapa_rs.plot(ax=ax, color=mapa_rs['cor'], edgecolor='dimgrey')
plt.title('Rede de TRM-TB no RS')
plt.show()